# Activity 6

### Q.No 1 Create a numpyarray of the shape (3,5): 3 rows and 5 columns  with random values from 1 to 100.

###    - Use np.random.randint(low,high, (shape))

In [46]:
import numpy as np
import pandas as pd

In [47]:
array = np.random.randint(low=1, high=100, size=(3,5))
print("Numpy array having 3 Row ad 5 columns")
print(array)

Numpy array having 3 Row ad 5 columns
[[88 40 56  3 73]
 [41 73 88 50 79]
 [22 49 11 57 56]]

In [48]:
# array.size

### Q.No 2 Use the numpyarray to generate a Data Frame with index = a,b,c and columns 1,2,3,4, 5•

In [49]:
df = pd.DataFrame(
    data = array, 
    columns = [1,2,3,4,5], 
    index = ['a', 'b', 'c']  # if no of rows != no of indices then error will occure.
    )

In [50]:
df.head()

    1   2   3   4   5
a  88  40  56   3  73
b  41  73  88  50  79
c  22  49  11  57  56

### Best way to create data, columns and indices and then pass these variable as argument in function call?

In [51]:
columns = [1, 2, 3, 4, 5]
print(f"Columns : {columns}")

Columns : [1, 2, 3, 4, 5]

In [52]:
index = ["a", "b", "c"]
print(f"Index : {index}")

Index : ['a', 'b', 'c']

In [53]:
pd.DataFrame(data=array, columns= columns, index= index)

    1   2   3   4   5
a  88  40  56   3  73
b  41  73  88  50  79
c  22  49  11  57  56

#### Default indices:
   - Default indices is always integers(whole numbers)

In [54]:
pd.DataFrame(data= array, columns= columns)

    1   2   3   4   5
0  88  40  56   3  73
1  41  73  88  50  79
2  22  49  11  57  56

### Q.No 3 Transpose (using .T) the DataFrameand change the values less than 40 to 0 in the Data Frame.

In [55]:
df_transpose = df.T
df_transpose

    a   b   c
1  88  41  22
2  40  73  49
3  56  88  11
4   3  50  57
5  73  79  56

In [56]:
df.head()

    1   2   3   4   5
a  88  40  56   3  73
b  41  73  88  50  79
c  22  49  11  57  56

In [57]:
df < 40  # Binary form df

       1      2      3      4      5
a  False  False  False   True  False
b  False  False  False  False  False
c   True  False   True  False  False

In [58]:
df[ df < 40 ]  # df with false with NaN

      1   2     3    4   5
a   NaN NaN   NaN  3.0 NaN
b   NaN NaN   NaN  NaN NaN
c  22.0 NaN  11.0  NaN NaN

In [59]:
df[ df < 40 ] = 0  # Replace 0 where the condition is true

In [60]:
df

    1   2   3   4   5
a  88  40  56   0  73
b  41  73  88  50  79
c   0  49   0  57  56

### Or use the below method

In [ ]:
df.where(df >=40, 0) # Keeps original values where condition is True. Replaces values where condition is FALSE with given value (0)

    1   2   3   4   5
a  88  40  56   0  73
b  41  73  88  50  79
c   0  49   0  57  56

### Q.No 5 Also display all the numbers >500 as a list (without the index)

In [63]:
df[df > 500].values.tolist() # b/c now values where found which is satisfying the condtion.

[[nan, nan, nan, nan, nan],
 [nan, nan, nan, nan, nan],
 [nan, nan, nan, nan, nan]]